import { Injectable } from '@angular/core';
import {
  Carrier,
  Policy,
  PolicyStatus,
  SourceOfLead,
} from '../interfaces/policy.interface';

@Injectable({
  providedIn: 'root',
})
export class PolicyService {
  private policy: Policy[] = [
    {
      id: 1,
      policy_type: 'MAPD',
      status: PolicyStatus.pending_cms,
      carrier: Carrier.humana,
      assignedTo: 'Patricia Garcia',
      agent_one: 'James Martinez',
      agent_two: 'April Gibson',
      date_Sale_made: '2024-10-04',
      effective_Date: '2025-09-20',
      contact: 'Jennifer Singh',
      source_of_lead: SourceOfLead.country,
      policy_number: 'HD84-0245',
      medicare_number: '688-80-5429',
      plan_and_network_id: 'PLAN-2887',
      old_ma_plan: 'Rocha-Thomas',
      old_ma_premium: '$144.00',
      new_ma_plan: 'Reynolds, Obrien and Hoover',
      new_ma_premium: '$139.00',
      sep: 'during concern order',
      prescriptions: 'each may effort through',
      contact_dob: '1950-08-07',
      part_a_sale_date: '2023-06-16',
      part_b_sale_date: '2023-07-15',
      doctors: ['Andrew Warner'],
      medications: ['develop', 'effort'],
    },
    {
      id: 2,
      policy_type: 'Medicare Supplement',
      status: PolicyStatus.active,
      carrier: Carrier.anthem_enclave,
      assignedTo: 'Tiffany Oconnell',
      agent_one: 'Angela Carlson',
      agent_two: 'Tracy Alexander',
      date_Sale_made: '2024-12-03',
      effective_Date: '2025-09-11',
      contact: 'Matthew Rogers',
      source_of_lead: SourceOfLead.country,
      policy_number: 'KY25-0981',
      medicare_number: '344-61-2481',
      plan_and_network_id: 'PLAN-3992',
      old_ma_plan: 'Brown-Rivera',
      old_ma_premium: '$193.00',
      new_ma_plan: 'Ballard, Morgan and Gonzalez',
      new_ma_premium: '$66.00',
      sep: 'them dark under page',
      prescriptions: 'usually describe leave service',
      contact_dob: '1936-08-28',
      part_a_sale_date: '2023-08-14',
      part_b_sale_date: '2023-03-19',
      doctors: ['Joseph Rodgers'],
      medications: ['blue', 'hard'],
    },
    {
      id: 3,
      policy_type: 'PDP',
      status: PolicyStatus.pending,
      carrier: Carrier.bcbs_empire_ny,
      assignedTo: 'Tasha Hill',
      agent_one: 'Andrea Tucker',
      agent_two: 'Stephanie Mann',
      date_Sale_made: '2024-10-18',
      effective_Date: '2025-09-27',
      contact: 'Robert Roman',
      source_of_lead: SourceOfLead.pop,
      policy_number: 'QT53-2735',
      medicare_number: '533-91-7060',
      plan_and_network_id: 'PLAN-1884',
      old_ma_plan: 'Ramirez, Henderson and Griffin',
      old_ma_premium: '$198.00',
      new_ma_plan: 'Pena, Swanson and Simpson',
      new_ma_premium: '$106.00',
      sep: 'attack try wait loss',
      prescriptions: 'on rather word respond',
      contact_dob: '1935-12-01',
      part_a_sale_date: '2023-11-23',
      part_b_sale_date: '2023-08-10',
      doctors: ['Cheryl Washington', 'Lindsay Maldonado'],
      medications: ['hope', 'around', 'argue'],
    },
    {
      id: 4,
      policy_type: 'Medicare Supplement',
      status: PolicyStatus.cancelled,
      carrier: Carrier.wellcare_allwell,
      assignedTo: 'Mark Norman',
      agent_one: 'Samantha Gordon',
      agent_two: 'Deborah Harris',
      date_Sale_made: '2024-08-27',
      effective_Date: '2025-08-23',
      contact: 'Angela Lopez',
      source_of_lead: SourceOfLead.reggae,
      policy_number: 'JJ76-1968',
      medicare_number: '336-87-0071',
      plan_and_network_id: 'PLAN-2911',
      old_ma_plan: 'Jones, Stewart and Montgomery',
      old_ma_premium: '$168.00',
      new_ma_plan: 'Patterson Inc',
      new_ma_premium: '$130.00',
      sep: 'chance become season simple',
      prescriptions: 'allow dark support stock',
      contact_dob: '1937-01-10',
      part_a_sale_date: '2024-04-14',
      part_b_sale_date: '2023-11-07',
      doctors: ['Ronnie Patel'],
      medications: ['prepare', 'safe'],
    },
    {
      id: 5,
      policy_type: 'MAPD',
      status: PolicyStatus.future_cancellation,
      carrier: Carrier.devoted,
      assignedTo: 'Stephen Klein',
      agent_one: 'Dr. Rachel Figueroa',
      agent_two: 'Edward Mendoza',
      date_Sale_made: '2024-12-18',
      effective_Date: '2025-09-24',
      contact: 'Cassandra Cohen',
      source_of_lead: SourceOfLead.hip_hop,
      policy_number: 'EK28-7753',
      medicare_number: '689-70-2926',
      plan_and_network_id: 'PLAN-3956',
      old_ma_plan: 'Thomas-Gordon',
      old_ma_premium: '$169.00',
      new_ma_plan: 'Snyder, Barrett and Myers',
      new_ma_premium: '$128.00',
      sep: 'move number country group',
      prescriptions: 'fall any social interest',
      contact_dob: '1936-07-23',
      part_a_sale_date: '2023-12-30',
      part_b_sale_date: '2023-05-11',
      doctors: ['Cynthia Thomas'],
      medications: ['quickly', 'minute'],
    },
  ];

  constructor() {}

  getAllPolicy(): Policy[] {
    return this.policy;
  }

  getPolicyById(id: number): Policy | undefined {
    return this.policy.find((policy) => policy.id === id);
  }
}
